name: Enriquecer Playlist desde TMDB

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install --no-cache-dir requests

      - name: Ejecutar script de enriquecimiento
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          python scripts/enrich.py

      - name: Listar y subir artifact
        run: |
          ls -lh .
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: enriched-playlist
          path: playlist.enriched.json

      - name: Commit and Push enriched JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.enriched.json
          if ! git diff --cached --exit-code; then
            git commit -m "Actualizar playlist.enriched.json"
            git push
          else
            echo "No hay cambios en playlist.enriched.json"
          fi
