# .github/workflows/enrich_playlist.yml
name: Enriquecer Playlist desde TMDB (REST)

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir requests

      - name: Enriquecer playlist.json con TMDB (REST API)
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          python <<EOF
          import os, json, requests

          api_key = os.environ['TMDB_API_KEY']
          base_search = 'https://api.themoviedb.org/3/search/movie'
          base_movie  = 'https://api.themoviedb.org/3/movie'

          with open('playlist.json', encoding='utf-8') as f:
              data = json.load(f)

          enriched = []
          for item in data:
              sample = item['samples'][0]
              original_title = sample['name']
              year  = sample.get('anio','').strip()

              # Buscar en TMDB con idioma español
              params = {
                  'api_key': api_key,
                  'language': 'es-MX',
                  'query': original_title,
                  'year': year
              }
              resp_search = requests.get(base_search, params=params).json()
              results = resp_search.get('results',[])
              if not results:
                  enriched.append(item)
                  continue

              movie = results[0]
              movie_id = movie['id']

              # Detalles en español
              resp_det = requests.get(f"{base_movie}/{movie_id}", params={
                  'api_key': api_key,
                  'language': 'es-MX'
              }).json()

              # Imágenes
              resp_imgs = requests.get(f"{base_movie}/{movie_id}/images", params={
                  'api_key': api_key
              }).json()

              # Campos TMDB
              spanish_title = resp_det.get('title') or original_title
              all_genres     = [g['name'] for g in resp_det.get('genres',[])]
              desc           = resp_det.get('overview','').strip()
              release_date   = resp_det.get('release_date','')
              release_year   = release_date[:4] if release_date else year
              duration       = resp_det.get('runtime',0)
              poster_path    = resp_det.get('poster_path')
              backdrop_path  = resp_det.get('backdrop_path')
              poster         = f"https://image.tmdb.org/t/p/original{poster_path}"   if poster_path   else ""
              backdrop       = f"https://image.tmdb.org/t/p/original{backdrop_path}" if backdrop_path else ""
              logos          = resp_imgs.get('logos',[])
              logo_url       = f"https://image.tmdb.org/t/p/original{logos[0]['file_path']}" if logos else ""

              # Construir registro enriquecido
              new_item = {
                  "name": all_genres[0] if all_genres else "",
                  "samples": [{
                      "name": spanish_title,
                      "url": sample['url'],
                      "icono": poster,
                      "iconoHorizontal": backdrop,
                      "iconpng": logo_url,
                      "type": "PELICULA",
                      "descripcion": desc,
                      "anio": release_year,
                      "genero": all_genres,
                      "duracion": f"{duration} min"
                  }]
              }
              enriched.append(new_item)

          # Guardar JSON enriquecido
          with open('playlist.enriched.json','w',encoding='utf-8') as f:
              json.dump(enriched, f, indent=2, ensure_ascii=False)
          EOF

      - name: Commit and push enriched JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.enriched.json
          if ! git diff --cached --exit-code; then
            git commit -m "Agregar datos TMDB a playlist"
            git push
          else
            echo "No hay cambios en playlist.enriched.json"
          fi
