# .github/workflows/generate_m3u.yml
name: Generar M3U desde VODS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        pip install --no-cache-dir requests beautifulsoup4

    - name: Generar playlist.m3u
      run: |
        python << 'EOF'
        import requests
        from bs4 import BeautifulSoup

        base_url = 'http://144.217.70.79/VODS-M/1080P/'
        resp = requests.get(base_url)
        resp.raise_for_status()

        soup = BeautifulSoup(resp.text, 'html.parser')
        lines = ['#EXTM3U']

        for link in soup.find_all('a', href=True):
            href = link['href']
            if href.lower().endswith('.mkv'):
                # URL completa
                video_url = base_url + href
                # Nombre sin extensión
                title = href.rsplit('/', 1)[-1].rsplit('.', 1)[0]
                lines.append(f'#EXTINF:-1 tvg-name="" tvg-id="" tvg-logo="" group-title="",{title}')
                lines.append(video_url)

        with open('playlist.m3u', 'w') as f:
            f.write('\n'.join(lines))
        EOF

    - name: Commit y push de playlist.m3u
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist.m3u
        # Solo commitea si hay cambios
        if ! git diff --cached --exit-code; then
          git commit -m "Actualizar playlist.m3u"
          git push
        else
          echo "No hay cambios en playlist.m3u"
        fi
